service: product-service
frameworkVersion: '3'
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  profile: personalAccount
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    PG_PORT: ${env:PG_PORT}
    PG_DATABASE: ${env:PG_DATABASE}
    PG_USERNAME: ${env:PG_USERNAME}
    PG_PASSWORD: ${env:PG_PASSWORD}
    PG_HOST: ${env:PG_HOST}
functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          method: get
          path: products
          cors: true
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          method: get
          path: 'products/{id}'
          cors: true
  addProduct:
    handler: handler.addProduct
    events:
      - http:
          method: post
          path: 'products'
          cors: true
