service: import-service

frameworkVersion: '3'
custom:
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  profile: personalAccount
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    PG_HOST: "${env:PG_HOST}"
    PG_PORT: "${env:PG_PORT}"
    PG_DATABASE: "${env:PG_DATABASE}"
    PG_USERNAME: "${env:PG_USERNAME}"
    PG_PASSWORD: "${env:PG_PASSWORD}"
  iamRoleStatements:
  - Effect: Allow
    Action: s3:ListBucket
    Resource:
    - arn:aws:s3:::node-in-aws-s3-pz
  - Effect: Allow
    Action:
    - s3:*
    Resource:
    - arn:aws:s3:::node-in-aws-s3-pz/*

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          method: get
          path: import
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: node-in-aws-s3-pz
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
              suffix: ".csv"
          existing: true
